[package]
name = "tocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
parking_lot = "0.12"
arc-swap = "1.5"

[dev-dependencies]
criterion = "0.3.5"
wg = "0.2.0"

[[bench]]
name = "bench_main"
harness = false