name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo check --features=dev-redis-impl,redis-impl

    - name: Test
      run: cargo test --features=dev-redis-impl,redis-impl
      env:
        REDIS_HOST: redis://localhost:6379

    - name: Clippy
      run: cargo clippy --tests --features=dev-redis-impl,redis-impl -- -Dwarnings
